# Generated by Django 3.1 on 2020-10-01 06:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=20, null=True)),
                ('phone_num', models.CharField(max_length=20, null=True)),
                ('team_state', models.IntegerField(default=0)),
                ('study_state', models.IntegerField(default=0)),
                ('intro', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('web_hearts', models.IntegerField(default=0)),
                ('design_hearts', models.IntegerField(default=0)),
                ('machine_learning_hearts', models.IntegerField(default=0)),
                ('statistics_hearts', models.IntegerField(default=0)),
                ('deep_learning_hearts', models.IntegerField(default=0)),
                ('algorithm_hearts', models.IntegerField(default=0)),
                ('nlp_hearts', models.IntegerField(default=0)),
                ('basic_python_hearts', models.IntegerField(default=0)),
                ('data_analysis_hearts', models.IntegerField(default=0)),
                ('voice_recog_hearts', models.IntegerField(default=0)),
                ('computer_vision_hearts', models.IntegerField(default=0)),
                ('rec_system_hearts', models.IntegerField(default=0)),
                ('reinforcement_hearts', models.IntegerField(default=0)),
                ('study_sum', models.IntegerField(default=0)),
                ('foreignkey', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='study', to='users.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('web', models.IntegerField(default=0)),
                ('design', models.IntegerField(default=0)),
                ('machine_learning', models.IntegerField(default=0)),
                ('statistics', models.IntegerField(default=0)),
                ('deep_learning', models.IntegerField(default=0)),
                ('algorithm', models.IntegerField(default=0)),
                ('nlp', models.IntegerField(default=0)),
                ('data_score', models.IntegerField(default=0)),
                ('modeling_score', models.IntegerField(default=0)),
                ('score_sum', models.IntegerField(default=0)),
                ('foreignkey', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='score', to='users.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_hearts', models.IntegerField(default=0)),
                ('web_hearts', models.IntegerField(default=0)),
                ('design_hearts', models.IntegerField(default=0)),
                ('modeling_hearts', models.IntegerField(default=0)),
                ('role_sum', models.IntegerField(default=0)),
                ('foreignkey', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='role', to='users.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('health', models.IntegerField(default=0)),
                ('economy', models.IntegerField(default=0)),
                ('culture_art', models.IntegerField(default=0)),
                ('education', models.IntegerField(default=0)),
                ('society', models.IntegerField(default=0)),
                ('technology', models.IntegerField(default=0)),
                ('domain_sum', models.IntegerField(default=0)),
                ('foreignkey', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='domain', to='users.customer')),
            ],
        ),
    ]
