# Generated by Django 3.1 on 2020-10-03 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.TextField()),
                ('title', models.TextField()),
                ('date', models.TextField()),
                ('content', models.TextField()),
                ('tag', models.TextField()),
                ('big_category', models.TextField()),
                ('category', models.TextField()),
                ('team_category', models.TextField()),
            ],
        ),
    ]
